spring.application.name=agrovalle-connect
spring.datasource.url=jdbc:postgresql://localhost:5432/agrovalle
spring.datasource.username=postgres
spring.datasource.password=TUCONTRASEÑA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
